version: "3.8"
services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - bank-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - bank-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - bank-network

  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - bank-network

  config-server:
    image: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - bank-network

  gateway-service:
    image: gateway-service
    build:
      context: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - bank-network

  client-service:
    image: client-service
    build:
      context: ./client-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - bank-network

  product-service:
    image: product-service
    build:
      context: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - bank-network

  movement-service:
    image: movement-service
    build:
      context: ./movement-service
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - bank-network

  report-service:
    image: report-service
    build:
      context: ./report-service
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - bank-network

  auth-service:
    image: auth-service
    build:
      context: ./auth-service
    ports:
      - "8085:8085"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - bank-network

  yanki-service:
    image: yanki-service
    build:
      context: ./yanki-service
    ports:
      - "8086:8086"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - bank-network

  bootcoin-service:
    image: bootcoin-service
    build:
      context: ./bootcoin-service
    ports:
      - "8087:8087"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
